
default: &default
  adapter: postgresql
  encoding: unicode
  username: cesar
  password: kele060990
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Quick_Orders_development
  
test:
  <<: *default
  database: Quick_Orders_test

production:
  <<: *default
  database: Quick_Orders_production
  username: Quick_Orders
  password: <%= ENV['QUICK_ORDERS_DATABASE_PASSWORD'] %>
